[package]
name = "vsproxy"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.4"
rand = "0.8"
rlimit = "0.10"
tokio-vsock = "0.4"
tokio = { version = "1.29", features = ["full"] }

[features]
all-tcp = []